### ISSUE TITLE
Build fails due to an a tag in a Link

### ISSUE THREAD

**Issue by alevann** [EsimioJ/kursaal#1]
When building the app the build fails with the following message (see full stacktrace below):
```
error - node_modules\next\dist\client\link.js (252:22) @ LinkComponent
error - Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
```

That error comes from `hero-post.js:26`:

```jsx
<Link href={`/posts/${slug}`}>
  <a
    className="hover:underline"
    dangerouslySetInnerHTML={{ __html: title }}
  />
</Link>
```

Changing that `a` to a `div` does the trick and the app builds without issue.

<details>
<summary>Full stacktrace</summary>

```
error - node_modules\next\dist\client\link.js (252:22) @ LinkComponent
error - Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
    at LinkComponent (webpack-internal:///./node_modules/next/dist/client/link.js:249:23)
    at renderWithHooks (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderForwardRef (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5842:18)
    at renderElement (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6005:11)
    at renderNodeDestructiveImpl (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6076:14)
    at renderNode (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6259:12)
    at renderHostElement (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5642:3)
    at renderElement (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (C:\Users\Alessandro\Downloads\kursaal-main\node_modules\react-dom\cjs\react-dom-server.browser.development.js:6104:11) {
  page: '/'
}
```

</details>

**Comment by EsimioJ** [comment]
thanks mate! ;-)
